# Generated by Django 4.1.7 on 2023-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaciones',
            name='altura',
            field=models.FloatField(default=-1),
        ),
    ]
